M48
; DRILL file {KiCad 8.0.5} date 2025-04-27T01:42:07+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-27T01:42:07+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X5.5706Y-3.2241
X5.5706Y-3.3973
X5.5706Y-3.8335
X5.5706Y-4.0067
T2
X3.563Y-2.4478
T3
X2.7362Y-2.4478
T4
X2.2744Y-2.3299
X4.0295Y-2.3299
M30
